# Generated by Django 4.1.2 on 2023-01-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created"],
                "verbose_name": "proyectos",
                "verbose_name_plural": "proyectos",
            },
        ),
    ]
